# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Ficurinia"
license = "AGPL3"
licenselink = "https://gitlab.com/gabmus/hugo-ficurinia/-/blob/master/LICENSE"
description = ""
homepage = "https://gitlab.com/gabmus/hugo-ficurinia"
tags = []
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.41.0"

logo = "/img/logo.png"

[author]
  name = "Gabriele Musco"
  homepage = "https://gabmus.org"
